POST https://auth-book.herokuapp.com/api/tokens
Content-Type: application/json

{
  "username": "shohrukh",
  "password": "pass"
}

> {% client.global.set("auth_token", response.body.token); %}

###

GET http://localhost:9999/api/purchases/users/1
Authorization: Bearer {{auth_token}}

###

DELETE http://localhost:9999/api/purchases/1
Authorization: Bearer {{auth_token}}

###
POST http://localhost:9999/api/purchases/0
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "product_id": 13,
  "price": 50120,
  "quantity": 10,
  "pic": "deee"
}

###

POST https://auth-book.herokuapp.com/api/tokens
Content-Type: application/json

{
  "username": "Ali",
  "password": "pass"
}

> {% client.global.set("auth_token", response.body.token); %}

###

GET https://booksstorageshop.herokuapp.com/api/products
Authorization: Bearer {{auth_token}}

###

POST https://booksstorageshop.herokuapp.com/api/products/0
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "name": "hercules",
  "description": "history",
  "price": 60,
  "pic": "56s"
}

###

DELETE https://booksstorageshop.herokuapp.com/api/products/3
Authorization: Bearer {{auth_token}}

###

